# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 008f8307c8ae235b213aabb8cbac43009f2dfea26fd357a13ad62ac04f1cc03ff3317ed3b43951c8a4f710c65414bc232fb4f9547c338c1db064d27d34695f3c

test:
  secret_key_base: 2c0213d43053a7de21f8f521f5ab64fd664219d4313fcaaa68ea55a2e40f8744fe5e61e4a32f4f74475611b3e5676666a0e805ac8fd4df12d08ed53c6f44d9f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
